name: Azure Pipelines

trigger:
  - main

pool: mypool

variables:
  python.version: "3.7.6"
  azureServiceConnectionId: UdacityDS - 82
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: "test"

stages:
  #--------------------------------------------#
  # BUILD STAGE
  #--------------------------------------------#
  - stage: Build
    jobs:
      - job: BuildInfrastructure
        steps:
          #--------------------------------------------#
          # Use Terraform to create the Infrastructure
          # Install Terraform on the pipeline agent
          - bash: |
              echo "hello"
              pwd
              ls -l
